services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - "3306:3306"
    volumes:
      - ./server/db/master/conf:/etc/mysql/conf.d
      - master_data:/var/lib/mysql

  mysql_slave1:
    image: mysql:8.0
    container_name: mysql_slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - "3307:3306"
    volumes:
      - ./server/db/slave1/conf:/etc/mysql/conf.d
      - slave1_data:/var/lib/mysql
    depends_on:
      - mysql_master

  mysql_slave2:
    image: mysql:8.0
    container_name: mysql_slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - "3308:3306"
    volumes:
      - ./server/db/slave2/conf:/etc/mysql/conf.d
      - slave2_data:/var/lib/mysql
    depends_on:
      - mysql_master

  backend1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend1
    volumes:
      - ./server:/app 
    environment:
      DB_HOST: mysql_master
      DB_USER: root
      DB_PASS: 111
      DB_NAME: voting_system
      DB_INIT: true
    depends_on:
      - mysql_master
    ports:
      - "3000:3000"

  backend2:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend2
    volumes:
      - ./server:/app   
    environment:
      DB_HOST: mysql_master
      DB_USER: root
      DB_PASS: 111
      DB_NAME: voting_system
    depends_on:
      - mysql_master
    ports:
      - "3001:3000"

  backend3:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend3
    volumes:
      - ./server:/app  
    environment:
      DB_HOST: mysql_master
      DB_USER: root
      DB_PASS: 111
      DB_NAME: voting_system
    depends_on:
      - mysql_master
    ports:
      - "3002:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend1


volumes:
  master_data:
  slave1_data:
  slave2_data:
